project:
  type: website
  output-dir: docs
website:
  favicon: favicon.png
  title: "About Cavell"
  navbar:
    logo: logo.png
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: games.qmd
        text: Games
      - href: Reflection.qmd
        text: Reflection

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
    toc-depth: 3
    toc-location: left


